### ISSUE TITLE
Add flag to ignore unused endpoint parameters

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/cask#39]
Currently, you cannot write an endpoint that takes a dynamic set of query parameters by manipulating `req.queryParams`, as unknown query parameters are rejected during input validation. While that's a reasonable default, we should provide a flag to disable that validation so a developer can work with `req.queryParams` fully dynamically if that's what they want

**Comment by jodersky** [comment]
FYI, I had a protoype here https://github.com/lihaoyi/cask/pull/34. I didn't go through with it, because I thought the place where the flag was defined was too obscure. Maybe that can be improved however.

As a side note, when I closed that issue I also came up with a workaround by defining my own HttpEndpoint: https://github.com/lihaoyi/cask/pull/34#issuecomment-678627134

**Comment by lihaoyi** [comment]
Yeah we ended up with a custom endpoint as well; we just subclassed `@cask.get` and made it pass `Map()` as the arguments. Works well enough, but would be nice to have a simple flag

**Comment by lihaoyi** [comment]
Fixed by https://github.com/com-lihaoyi/cask/pull/108
