### ISSUE TITLE
Twirl template gets wrapped by additional HTML

### ISSUE THREAD

**Issue by razem-io** [com-lihaoyi/cask#72]
Hi, thank you for the great project. I ran into an issue, which prevents me from using twirl. Scalatags works without issues.

```
package app
object Twirl extends cask.MainRoutes{
  @cask.get("/")
  def hello() = {
    "<!doctype html>" + html.hello("Hello World")
  }

  initialize()
}
```

This example from the [docs](https://com-lihaoyi.github.io/cask/index.html#html-rendering) does not work. It gets wrapped by additional HTML instead:

```
<html data-lt-installed="true"><head><meta name="color-scheme" content="light dark"></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">&lt;!doctype html&gt;&lt;html&gt;
&lt;body&gt;
&lt;h1&gt;Hello World&lt;/h1&gt;
&lt;p&gt;I am cow&lt;/p&gt;
&lt;/body&gt;
&lt;/html&gt;</pre></body></html>
```

**Comment by razem-io** [comment]
Got it to work using scalatags and twirl, which kinda defeats the purpose:

```
  @cask.get("/")
  def hello() = {
    doctype("html")(
      raw(
        de.headnap.tuersteher.html.index().toString()
      )
    )
  }
```

**Comment by sherpal** [comment]
That's because when you do `"<!doctype html>" + html.hello("Hello World")`, you have a `String`, which cask sends back by default as `text/plain`.

So instead of wrapping in scalatags (although it works), you should change the `Content-Type` of the response.

**Comment by razem-io** [comment]
Thank you for the quick response. Can you give a concrete example? In the docs, nothing like that is mentioned. I can create a PR later.

https://com-lihaoyi.github.io/cask/index.html#html-rendering

**Comment by razem-io** [comment]
This works. Less boilerplate would be nice. I guess I could write a TwirlResponse class? What is best practice here?
```
@cask.get("/")
  def hello() = {
    def r = index.render()

    cask.Response(
      data = r.toString(),
      headers = Seq("Content-Type" -> r.contentType)
    )
  }
```

**Comment by irramail** [comment]
package app
object Twirl extends cask.MainRoutes{
  @cask.get("/")
    def hello() = {
      cask.Response(
          "<!doctype html>" + html.hello("Hello World"),
          headers = Seq("Content-type" -> "text/html")
        )
            }
  initialize()
}

**Comment by lihaoyi** [comment]
I believe the proper way to handle this is via

```scala
  @cask.get("/")
  def hello() = {
    doctype("html")(
      html.index()
    )
  }
```

This is covered in the docs for [HTML Rendering](https://com-lihaoyi.github.io/cask/#html-rendering)

**Comment by lihaoyi** [comment]
I think the way you have done it is about the best we can do. The docs are wrong. Twirl does not know about Cask, Cask does not know about Twirl, and neither of them share a common interface. In contrast, both Cask and Scalatags know about [geny.Writable#httpContentType](https://github.com/com-lihaoyi/geny/blob/332c75d59dae5f3cce0c8c547f8d92da43c6ad36/geny/src/geny/Writable.scala#L26-L28), which is why they are able to interop smoothly.

The correct solution here is to send a PR to Twirl so that its output type is a subclass of `geny.Writable`, with a proper `httpContentType` override. This would let it behave properly when returned from a Cask route, without hardcoded interdependencies between Cask and Twirk
